version: "3.9"

services:
  i2pd:
    build:
      context: .
      dockerfile: Dockerfile.i2pd
    container_name: i2pd
    volumes:
      - ./tunnel.conf:/home/i2pd/data/tunnels.conf
    restart: unless-stopped
  outproxys:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: outproxys
    restart: unless-stopped
    depends_on:
      - i2pd
    environment:
      I2PD_SOCKS_HOST: "i2pd"
      I2PD_SOCKS_PORT: "4447"
    ports:
      - "9313:9313"

volumes:
  i2pd_data:
