FROM purplei2p/i2pd:latest
USER root
RUN apk add --no-cache socat curl links

#RUN mkdir -p /home/i2pd/data/tunnels.conf.d
#COPY tunnel.conf /home/i2pd/data/tunnels.conf.d/tunnel.conf
#RUN chown -R i2pd /home/i2pd/data/tunnels.conf.d
#COPY tunnel.conf /home/i2pd/data/tunnels.conf
#RUN mkdir -p /home/i2pd/data/tunnels.conf.d

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
USER i2pd
ENTRYPOINT ["/entrypoint.sh"]
