name: Build All Platforms

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [amd64, arm64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.25

      - name: Build binary
        run: |
          mkdir -p bin
          GOOS=$(
            case "${{ matrix.os }}" in
              ubuntu-latest) echo "linux" ;;
              windows-latest) echo "windows" ;;
              macos-latest) echo "darwin" ;;
            esac
          )
          GOARCH=${{ matrix.arch }}
          EXT=""
          [ "$GOOS" = "windows" ] && EXT=".exe"
          go build -o bin/outproxys-${GOOS}-${GOARCH}${EXT}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: outproxys-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/

